sonar.projectKey=elevate-flutter-team_CI-CD-C5_flutter
sonar.organization=elevate-flutter-team-1

# This is the name and version displayed in the SonarCloud UI.
sonar.projectName=CI-CD-C5_flutter
sonar.projectVersion=1.0

# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
sonar.sources=lib
sonar.tests=test

# Encoding of the source code. Default is default system encoding
sonar.language=dart
sonar.sourceEncoding=UTF-8
sonar.dart.lcov.reportPaths=coverage/lcov.info

# Exclude generated files (optional but recommended)
sonar.exclusions=**/*.g.dart, **/*.freezed.dart, lib/generated/**